version: "3.7"
services:
  print:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-dev:1.3
    container_name: gestsis-print
    restart: unless-stopped
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "yarn && node app.js"
